Adjust to support SOX Sequoia and latest software versions

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -1,4 +1,19 @@
 #!/bin/sh
+if [ -z "$PROFILE" ]; then
+  echo "PROFILE environment variable not set, please set it to the profile you want to use (e.g. export PROFILE=work)"
+  exit 1
+fi
+
+if [ -z "$GIT_USER_NAME" ]; then
+  echo "GIT_USER_NAME environment variable not set, please set it to your git user name (e.g. export GIT_USER_NAME='John Doe')"
+  exit 2
+fi
+
+if [ -z "$GIT_USER_EMAIL" ]; then
+  echo "GIT_USER_EMAIL environment variable not set, please set it to your git user email (e.g. export GIT_USER_EMAIL='jane.doe@example.com')"
+  exit 3;
+fi
+
 check=$((xcode-\select --install) 2>&1)
 str="xcode-select: note: install requested for command line developer tools"
 while [[ "$check" == "$str" ]];
@@ -7,16 +22,21 @@ do
   exit;
 done
 
-# xcode-select -p
-# if not successfull then:
-xcodebuild -license
-# on only do this on apple silicon
-# /usr/sbin/softwareupdate --install-rosetta
-git config --global http.postBuffer 524288000
-curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
-python3 get-pip.py
-sudo pip3 install --ignore-installed ansible
-ansible-galaxy role install -r requirements.yml
-ansible-galaxy collection install -r requirements.yml
-# Stop screen saver before starting to stop homebrew failing to download inital update force.
-ansible-playbook -i "localhost," -c local ansible_osx.yml --ask-become-pass
+if [ ! -d ansible ]; then
+  # on only do this on apple silicon
+  # /usr/sbin/softwareupdate --install-rosetta
+  git config --global http.postBuffer 524288000
+  # curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
+  # python3 get-pip.py
+  python3 -m venv ansible  # Create a virtualenv if one does not already exist
+  source ansible/bin/activate   # Activate the virtual environment
+  python3 -m pip install --upgrade pip
+  pip3 install ansible
+  #sudo pip3 install --ignore-installed ansible
+  ansible-galaxy role install -r requirements.yml
+  ansible-galaxy collection install -r requirements.yml
+  # Stop screen saver before starting to stop homebrew failing to download inital update force.
+else
+  source ansible/bin/activate   # Activate the virtual environment
+fi
+ansible-playbook -i "localhost," -c local ansible_osx.yml -e "@configuration/${PROFILE}.yml" --ask-become-pass
